function(check64Bit resultHolder)

	if( CMAKE_SIZEOF_VOID_P EQUAL 8 )
		set(${resultHolder} ON PARENT_SCOPE) 
	else()
		set(${resultHolder} OFF PARENT_SCOPE) 
	endif()

endfunction()

function(setBuildFolder)
	
	check64Bit(is64Bit)

	if( is64Bit )
		message(STATUS"------------------------  This is a 64bit build ${CMAKE_BUILD_TYPE}" )
		foreach( OUTPUTCONFIG ${CMAKE_CONFIGURATION_TYPES} )
			string( TOUPPER ${OUTPUTCONFIG} OUTPUTCONFIG )
			set( CMAKE_RUNTIME_OUTPUT_DIRECTORY_${OUTPUTCONFIG} "${CMAKE_BINARY_DIR}/x64/${OUTPUTCONFIG}" )
			set( CMAKE_LIBRARY_OUTPUT_DIRECTORY_${OUTPUTCONFIG} "${CMAKE_BINARY_DIR}/x64/${OUTPUTCONFIG}" )
			set( CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${OUTPUTCONFIG} "${CMAKE_BINARY_DIR}/x64/${OUTPUTCONFIG}" )
		endforeach( OUTPUTCONFIG CMAKE_CONFIGURATION_TYPES )
	else()
		message(STATUS"------------------------  This is a 32bit build ${CMAKE_BUILD_TYPE}" )
		foreach( OUTPUTCONFIG ${CMAKE_CONFIGURATION_TYPES} )
			string( TOUPPER ${OUTPUTCONFIG} OUTPUTCONFIG )
			set( CMAKE_RUNTIME_OUTPUT_DIRECTORY_${OUTPUTCONFIG} "${CMAKE_BINARY_DIR}/x86/${OUTPUTCONFIG}" )
			set( CMAKE_LIBRARY_OUTPUT_DIRECTORY_${OUTPUTCONFIG} "${CMAKE_BINARY_DIR}/x86/${OUTPUTCONFIG}" )
			set( CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${OUTPUTCONFIG} "${CMAKE_BINARY_DIR}/x86/${OUTPUTCONFIG}" )
		endforeach( OUTPUTCONFIG CMAKE_CONFIGURATION_TYPES )
	endif()

endfunction()