######################################################
#######  m2mo Laure Elie TP1 Applications   ##########
######################################################

#!!! Set the PROJECT_ROOT_DIRECTORY as the working directory
## i.e ".." from this file

## Regression pseudo inverse also called "Moore-Penrose pseudoinvers"
## http://en.wikipedia.org/wiki/Moore%E2%80%93Penrose_pseudoinverse

## starting by importing data
datatab=read.table("data/Expseudo.txt", header=TRUE, sep=";") # Read the data file from the data folder
dimtab<-dim(datatab)
## we see that n=20 and p = 7-1 = 6

### Question 1 
## Computing the covariance matrix of explanator variables
cov_X<-cov(datatab[,1:6])
## X3 and X6 has high variance

### Question 2
## binding data for having the design matrix
X<-as.matrix(cbind(rep(1, dimtab[1]) ,datatab[,1:6])) 
S<- t(X)%*%X
solve(S)
## the solve function in R say that the system is not invertible
## Singular Value Decomposition 
S.svd<-svd(S)
S.svd$d
## By looking in to the singular value list, the two last elements are very closed to zero
## That say the matrix is non invertible, or numerically very difficult to invert

### Question 3
## If S is real matrix, S+ has to satisfy 4 conditions
## S.S+.S   = S         S.S+ is an "approach" of I, in the way that S+ is an approach of S^-1
## S+.S.S+  = S+        
## (S.S+)^t = S.S+     S.S+ and S+.S is symetric matrix (hermitian in complex case)
## (S+.S)^t = S+.S


### Question 4
InvertedSigma1<-diag(1/(S.svd$d[1:5]),5,5)
U_1<-as.matrix(S.svd$u[,1:5])
U_2<-as.matrix(S.svd$u[,6:7])
beta1star<-InvertedSigma1%*%t(U_1)%*%t(X)%*%datatab[,7]
betastar<- U_1%*%beta1star

### Question 5   ------------------------------------------> to asked why QES too small
## computed fitted data and 
fitted_Y<-X%*%betastar
residual_star_square<-sum( (fitted_Y-datatab[,7])*(fitted_Y-datatab[,7]) )
residual_star<-sum(fitted_Y-datatab[,7])


### Question 6
## solution set of the problem is the affine subspace of R^p which have dimension 2
## defined by the formula beta_hash = U_1%*%beta1star + U_2%*%beta2hat

### Question 7
##
##
norm1<-sqrt(sum(beta1star*beta1star))
norm2<- sqrt( 10000*10000 - norm1*norm1)
beta2test<-c(norm2,0)
beta_question7<- U_1%*%beta1star + U_2%*%beta2test
#test norm of beta_question7
norm7 =  sqrt(sum(beta_question7*beta_question7))


### Question 8   ---> to ask
## Because beta1star is the projection of Y to the subspace generated by the k nonsingular columm vector in X
##

### Question 9
reverse.lm<-lsfit(datatab[,1:6], datatab[,7],tolerance=1e-16)
Y_F = X%*%reverse.lm$coefficients
EQM<- sum((Y_F-datatab[,7])*(Y_F-datatab[,7]))
EM<- sum(Y_F-datatab[,7])

